require: rubocop-rspec

Metrics/ClassLength:
  Max: 200

Style/Documentation:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/BlockDelimiters:
  EnforcedStyle: semantic
