sudo: false

language: ruby

cache: bundler

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: 2.3.3
    - rvm: 2.4.0
    - rvm: ruby-head

cache: bundler

script:
  - bundle exec rake
